version: '3.8'

services:
  gpu-monitor:
    build: .
    container_name: gpu-monitor
    ports:
      - "8081:8081"
    environment:
      - TZ=America/Los_Angeles   # update your timezone
    volumes:
      - /etc/localtime:/etc/localtime:ro  # Share host timezone
      - ./history:/app/history    # Persist historical data on host
      - ./logs:/app/logs    # Persist logs
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    restart: unless-stopped
    runtime: nvidia